# basic options - is treated as a comment 

title: 22 
author: Mingya 
email: your-email@domain.com
description: A blog to caputre the jounery of my life after university 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
